# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build1:
    filters:
      branches:
        only:
          - development
    docker:
      # specify the version you desire here
      - image: circleci/node:12.9.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/merchant

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Install Dependencies
      - run:
          name: 'Install Dependencies'
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: .
          paths:
            - .
  build2:
    filters:
      branches:
        only:
          - development
    docker:
      # specify the version you desire here
      - image: circleci/node:12.9.0
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/merchant

    steps:
      - attach_workspace:
          at: .

      # Test Project
      - run:
          name: 'Build Project'
          command: yarn build

      - persist_to_workspace:
          root: .
          paths:
            - .

  build3:
    filters:
      branches:
        only:
          - development
    docker:
      # specify the version you desire here
      - image: circleci/node:12.9.0
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/merchant

    steps:
      - attach_workspace:
          at: .
      # Firebase Deploy
      - run:
          name: 'Deploy Development to Firebase'
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2
  build_deploy:
    jobs:
      - build1
      - build2:
          requires:
            - build1
      - build3:
          requires:
            - build1
            - build2
